---
server:
  port: 8111
config.someProperty: Example Service1 - Updated Value
---
spring:
    config:
        activate:
            on-profile: test            
server:
  port: 8110       
config.someProperty: Example Service1(test profile) - Updated Value
