---
server:
  port: 8111
config.someProperty: default profile value
---
spring:
    config:
        activate:
            on-profile: test            
server:
  port: 8110       
config.someProperty: value from test profile1
