server:
  port: 8110
config.someProperty: updated default profile value

---
spring:
    config:
        activate:
            on-profile: test
server:
  port: 8100            
config.someProperty: value from test profile2    
