---
server:
  port: 8115

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true


---
spring:
    config:
        activate:
            on-profile: test      

server:
  port: 8116
